language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
os:
 - linux
script:
 - dotnet restore ./BunBlog.sln
 - dotnet build ./src/Presentation/Bun.Blog.Web/Bun.Blog.Web.csproj --configuration Release --framework netcoreapp1.1